### ISSUE TITLE
K3S Traefik setup

### ISSUE THREAD

**Issue by ulexxander** [ulexxander/lab#1]
Std:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-21.2.1+up21.2.0.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      repository: "rancher/mirrored-library-traefik"
      tag: "2.9.10"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: "PreferDualStack"
```

Overrides:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: kube-system
stringData:
  users: ??????????????????

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: kube-system
spec:
  basicAuth:
    secret: basic-auth

---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      access:
        enabled: true

    deployment:
      kind: DaemonSet

    updateStrategy:
      type: OnDelete

    service:
      enabled: false

    ports:
      web:
        hostPort: 80
        redirectTo: websecure
      websecure:
        hostPort: 443
        tls:
          enable: true

    ingressRoute:
      dashboard:
        entryPoints:
          - websecure
        middlewares:
          - name: basic-auth
```

Kube dash:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kube-dashboard

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: kube-dashboard
spec:
  stripPrefix:
    prefixes:
      - /kubernetes-dashboard

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubernetes-dashboard
  namespace: kube-dashboard
spec:
  repo: https://kubernetes.github.io/dashboard
  chart: kubernetes-dashboard
  valuesContent: |
    nginx:
      enabled: false

    cert-manager:
      enabled: false

    metrics-server:
      enabled: false

    app:
      ingress:
        ingressClassName: traefik
        hosts: null
        paths:
          web: /kubernetes-dashboard
          api: /kubernetes-dashboard/api
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: strip-prefix
        issuer:
          name: disabled
```
