### ISSUE TITLE
Helm charts can be managed using plain K8S jobs

### ISSUE THREAD

**Issue by ulexxander** [ulexxander/lab#2]
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-monitoring
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-helm
  namespace: monitoring
data:
  RELEASE_NAME: grafana
  RELEASE_NAMESPACE: monitoring
  CHART_REPO: https://grafana.github.io/helm-charts
  CHART_NAME: grafana
  CHART_VERSION: 6.58.4
  RELEASE_VALUES: |
    ingress:
      enabled: true
      ingressClassName: nginx-internal
      hosts:
        - grafana.localhost

    persistence:
      type: pvc
      enabled: true
      storageClassName: ebs-reclaim-retain
      size: 10Gi
```

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-helm-install
  namespace: monitoring
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: helm
      containers:
        - name: helm
          image: alpine/helm
          command:
            - sh
            - -c
            - |
              set -ex
              echo "$RELEASE_VALUES" > /values.yaml
              helm repo add "$CHART_NAME" "$CHART_REPO"
              helm upgrade "$RELEASE_NAME" "${CHART_NAME}/${CHART_NAME}" \
                --namespace "$RELEASE_NAMESPACE" --install --wait \
                --version "$CHART_VERSION" --values /values.yaml
          envFrom:
            - configMapRef:
                name: grafana-helm
```

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-helm-uninstall
  namespace: monitoring
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: helm
      containers:
        - name: helm
          image: alpine/helm
          command:
            - sh
            - -c
            - |
              set -ex
              helm uninstall "$RELEASE_NAME" \
                --namespace "$RELEASE_NAMESPACE" --wait
          envFrom:
            - configMapRef:
                name: grafana-helm
```
